# EC2 instance variable

stack_name: "JenkinsAppianCICDSlave"
state: "present"
region: "ap-southeast-2"
infra_version: "1.0"
colour: "blue"

# security_groups : for CF stack
# security_group_ids : for non CF
ec2:
  ami_id: "ami-0faafb7f6d4b6129e"
  instance_type: "t2.medium"
  key_pair: "steven"
  iam_role: "S3FullAccess"
  vpc_subnet_id: "subnet-b37ccfd6"
  security_groups: "sg-0fa7c3d78dac64c06, sg-38c4da41"
  security_group_ids:
    - "sg-0fa7c3d78dac64c06"
    - "sg-38c4da41"
  assign_public_ip: "yes"
  tags:
    "Name": "Jenkins slave AMI Image"
    "exempted_date": "15/08/2018"
  volumes:
    - device_name: /dev/xvda
      volume_type: standard
      volume_size: 8
