# Create EC2 instance by CloudFormation
- name: Create EC2 Stack using Cloudformation
  cloudformation:
    stack_name: "{{ stack_name }}"
    state: "{{ state}}"
    region: "{{ region }}"
    disable_rollback: false
    template: "{{playbook_dir}}/roles/ec2-cf/files/ec2_template.yml"
    template_parameters:
      InstanceProfile: "{{ ec2.iam_role }}"
      AmiId: "{{ ec2.ami_id }}"
      InstanceType: "{{ ec2.instance_type }}"
      KeyName: "{{ec2.key_pair}}"
      SecurityGroup: "{{ ec2.security_groups }}"
    tags:
      "Environment": "{{ env_type }}"
      "exempted_date": "{{ ec2.tags.exempted_date }}"
      "nbn:applicationSource": "{{ ec2.tags.nbn:applicationSource }}"
      "nbn:env:code": "{{ ec2.tags.nbn:env:code }}"
      "nbn:env:subcode": "{{ ec2.tags.nbn:env:subcode }}"
      "nbn:focalPoint:applicationId": "{{ ec2.tags.nbn:focalPoint:applicationId }}"
      "nbn:focalPoint:applicationName": "{{ ec2.tags.nbn:focalPoint:applicationName }}"
      "nbn:focalPoint:applicationShortName": "{{ ec2.tags.nbn:focalPoint:applicationShortName }}"
      "nbn:focalPoint:sdgCode": "{{ ec2.tags.nbn:focalPoint:sdgCode }}"
      "nbn:focalPoint:sdgPlatformCode": "{{ ec2.tags.nbn:focalPoint:sdgPlatformCode }}"
      "nbn:focalPoint:sdgPlatformName": "{{ ec2.tags.nbn:focalPoint:sdgPlatformName }}"
      "nbn:focalPoint:systemTeamEmail": "{{ ec2.tags.nbn:focalPoint:systemTeamEmail }}"
      "nbn:focalPoint:systemTeamLead": "{{ ec2.tags.nbn:focalPoint:systemTeamLead }}"
      "nbn:focalPoint:systemTeamName": "{{ ec2.tags.nbn:focalPoint:systemTeamName }}"
      "nbn:operationalMode": "{{ ec2.tags.nbn:operationalMode }}"
      "nbn:teamCode": "{{ ec2.tags.nbn:teamCode }}"
      "state:scheduleName": "{{ ec2.tags.state:scheduleName }}"
  register: stack