# Create EC2 instance by CloudFormation
- name: Create EC2 Stack using Cloudformation
  cloudformation:
    stack_name: "{{ stack_name }}"
    state: "{{ state}}"
    region: "{{ region }}"
    disable_rollback: false
    template: "{{playbook_dir}}/roles/ec2-cf/files/ec2_template.yml"
    template_parameters:
      InstanceProfile: "{{ ec2.iam_role }}"
      AmiId: "{{ ec2.ami_id }}"
      InstanceType: "{{ ec2.instance_type }}"
      KeyName: "{{ec2.key_pair}}"
      SecurityGroup: "{{ ec2.security_groups }}"
    tags:
      "Environment": "{{ env_type }}"
      "exempted_date": "{{ ec2.tags.exempted_date }}"
      "nbn:applicationSource": "{{ ec2.tags.nbn_applicationSource }}"
      "nbn:env:code": "{{ ec2.tags.nbn_env_code }}"
      "nbn:env:subcode": "{{ ec2.tags.nbn_env_subcode }}"
      "nbn:focalPoint:applicationId": "{{ ec2.tags.nbn_focalPoint_applicationId }}"
      "nbn:focalPoint:applicationName": "{{ ec2.tags.nbn_focalPoint_applicationName }}"
      "nbn:focalPoint:applicationShortName": "{{ ec2.tags.nbn_focalPoint_applicationShortName }}"
      "nbn:focalPoint:sdgCode": "{{ ec2.tags.nbn_focalPoint_sdgCode }}"
      "nbn:focalPoint:sdgPlatformCode": "{{ ec2.tags.nbn_focalPoint_sdgPlatformCode }}"
      "nbn:focalPoint:sdgPlatformName": "{{ ec2.tags.nbn_focalPoint_sdgPlatformName }}"
      "nbn:focalPoint:systemTeamEmail": "{{ ec2.tags.nbn_focalPoint_systemTeamEmail }}"
      "nbn:focalPoint:systemTeamLead": "{{ ec2.tags.nbn_focalPoint_systemTeamLead }}"
      "nbn:focalPoint:systemTeamName": "{{ ec2.tags.nbn_focalPoint_systemTeamName }}"
      "nbn:operationalMode": "{{ ec2.tags.nbn_operationalMode }}"
      "nbn:teamCode": "{{ ec2.tags.nbn_teamCode }}"
      "state:scheduleName": "{{ ec2.tags.state_scheduleName }}"
      "nbn:ast:ownerName": "{{ ec2.tags.nbn_ast_ownerName }}"
      "nbn:ast:ownerEmail": "{{ ec2.tags.nbn_ast_ownerEmail }}"
      "nbn:ast:ownerMobile": "{{ ec2.tags.nbn_ast_ownerMobile }}"
  register: stack