#
# Create EC2 instance
- name: Create instances
  ec2:
    region: "{{ region }}"
    keypair: "{{ ec2.key_pair }}"
    image: "{{ ec2.ami_id }}"
    instance_type: "{{ ec2.instance_type }}"
    instance_profile_name: "{{ ec2.iam_role | default('') }}"
    group_id: "{{ ec2.security_group_ids }}"
    vpc_subnet_id: "{{ ec2.vpc_subnet_id }}"
    assign_public_ip: "{{ ec2.assign_public_ip | default('no') }}"
    private_ip: "{{ ec2.private_ip | default('') }}"
    wait: true
    instance_tags: |
          {
              "Name":"{{ ec2.tags.Name }}",
              "Type":"{{ ec2.tags.Type }}",
              "Environment":"{{ ec2.tags.Env }}"
          }
  register: ec2



- name: Create EC2 instance to setup front-end web server
  local_action:
    module: ec2
    key_name: "{{key_name}}"
    group: "default"
    instance_profile_name: "default-profile"
    instance_type: t2.micro
    image: "{{ami_id}}"
    region: "{{aws_region}}"
    zone: "{{aws_zone}}"
    user_data: "{{lookup('template', '../templates/cloud-init-script.j2')}}"
    wait: yes
  register: web_base