# Instance creation
# Run : ansible-playbook -i env/hosts create_ec2.yml
- hosts: localhost
  connection: local
  pre_tasks:
    - include_vars: group_vars/apmtest.yml
  roles:
    - ec2
  tags: ec2_create

